name: Manual Upload ZIP to Cloudsmith

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli

      - name: Upload to Cloudsmith (RAW)
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push raw simran-parwani-testorg/test-repo vault_1.17.5+ent.hsm_linux_amd64.zip \
          --name vault_1.17.5+ent.hsm_linux_amd64.zip \
          --version 1.17.5-hsm \
          --summary "Vault Enterprise HSM build for Linux AMD64" \
          --description "HashiCorp Vault 1.17.5+ent.hsm compiled for Linux AMD64 architecture"